/* AUTOMATICALLY GENERATED BY TOP-LEVEL MAKEFILE.PL -- DO NOT EDIT */


#define BUILDDIR "/local/wk/michel/freewrl/freewrl"
#define FWVER "V1.21.1"
#define XMESSAGE "/usr/bin/FreeWRL_Message"
#define SOUNDSERVERBINARY "/usr/bin/FreeWRL_SoundServer"
#define	BROWSER		"/usr/bin/mozilla"
#define	SOUNDCONV		"/usr/bin/sox"
#define	UNZIP		"/bin/gunzip"
#define	WGET		"/usr/bin/wget"
#define	CONVERT		"/usr/bin/convert"
#define	JAVA		"/usr/bin/java"
#define	FONTSDIR		"/usr/share/fonts/truetype/ttf-bitstream-vera"
