libEAI_la_SOURCES = \
			EAI_C_Advise.c \
			EAI_C_Control.c \
			EAI_C_Field.c \
			EAI_C_Internals.c \
			EAI_C_Node.c \
			EAI_C_ReWire.c \
			GeneratedCode.c

include_HEADERS = \
			EAI_C.h \
			GeneratedHeaders.h \
			X3DNode.h
