//AUTOMATICALLY GENERATED BY genexceptions.pl.
//DO NOT EDIT!!!!

package vrml;

public class InvalidEventInException extends IllegalArgumentException {
    public InvalidEventInException() { super(); }
    public InvalidEventInException(String s) { super(s); }
}
