//AUTOMATICALLY GENERATED BY genexceptions.pl.
//DO NOT EDIT!!!!

package vrml;

public class InvalidExposedFieldException extends IllegalArgumentException {
    public InvalidExposedFieldException() { super(); }
    public InvalidExposedFieldException(String s) { super(s); }
}
