//AUTOMATICALLY GENERATED BY genexceptions.pl.
//DO NOT EDIT!!!!

package vrml;

public class InvalidEventOutException extends IllegalArgumentException {
    public InvalidEventOutException() { super(); }
    public InvalidEventOutException(String s) { super(s); }
}
