//AUTOMATICALLY GENERATED BY genexceptions.pl.
//DO NOT EDIT!!!!

package vrml;

public class InvalidFieldException extends IllegalArgumentException {
    public InvalidFieldException() { super(); }
    public InvalidFieldException(String s) { super(s); }
}
