//AUTOMATICALLY GENERATED BY genexceptions.pl.
//DO NOT EDIT!!!!

package vrml;

public class InvalidRouteException extends IllegalArgumentException {
    public InvalidRouteException() { super(); }
    public InvalidRouteException(String s) { super(s); }
}
