//AUTOMATICALLY GENERATED BY genfields.pl.
//DO NOT EDIT!!!!

package vrml.field;
import vrml.*;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.IOException;

public class ConstSFString extends ConstField {
     String s;

    public ConstSFString() { }

    public ConstSFString(String s) {
	        this.s = s;
    }

    public String getValue() {
        __updateRead();
        return s;
    }

    public String toString() {
        __updateRead();
        return vrml.FWHelper.quote(s);
    }

    public void __fromPerl(BufferedReader in)  throws IOException {

	//System.out.println ("fromPerl, String");
		s = in.readLine();
    }

    public void __toPerl(PrintWriter out)  throws IOException {
        out.print(s);
	//out.println();
    }
    //public void setOffset(String offs) { this.offset = offs; } //JAS2
    //public String getOffset() { return this.offset; } //JAS2
}