//AUTOMATICALLY GENERATED BY genfields.pl.
//DO NOT EDIT!!!!

package vrml.field;
import vrml.*;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.IOException;

public class ConstSFFloat extends ConstField {
     float f;

    public ConstSFFloat() { }

    public ConstSFFloat(float f) {
	        this.f = f;
    }

    public float getValue() {
        __updateRead();
        return f;
    }

    public String toString() {
        __updateRead();
        return String.valueOf(f);
    }

    public void __fromPerl(BufferedReader in)  throws IOException {

	//System.out.println ("fromPerl, Float");
		f = Float.parseFloat(in.readLine());
    }

    public void __toPerl(PrintWriter out)  throws IOException {
        out.print(f);
	//out.println();
    }
    //public void setOffset(String offs) { this.offset = offs; } //JAS2
    //public String getOffset() { return this.offset; } //JAS2
}